"""added owners

Revision ID: 016498effadf
Revises: 3ece60e11bd3
Create Date: 2022-06-16 21:31:14.658930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016498effadf'
down_revision = '3ece60e11bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners')
    # ### end Alembic commands ###
